name: Test, Build and Publish to Github Container Registry

on: [push]

env:
  REGISTRY: 'ghcr.io'
  IMAGE_NAME: 'danilow/demo-msddo'
  DOCKERFILE_PATH: './Dockerfile'
  
permissions:
  packages: write # Needed to publish to Github Container Registry
  contents: read


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v2
      
      # Login to Github Container Registry
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Extract metadata from Dockerfile
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{ env.DOCKERFILE_PATH }}
               



