name: 'Credscan'

on: [push]

env:
  GDN_RUN_GITHUB: 'true' # When outputting a SARIF file, make the SARIF compliant with GitHub's code scanning requirements
  GDN_RUN_LOGGERACTIONS: 'true' # to enable logging in Github actions format.
  
permissions:
  security-events: 'write' # Needed to run MSDDO
jobs:

    MSDO:
        name: MSDDO Credscan scan on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
              os: [windows-latest, ubuntu-latest]
        steps:
            # Checkout your code repository to scan
            - uses: actions/checkout@v3

            # Run analyzers
            - name: Run Credscan Analysis using Microsoft Defender for DevOps
              uses: microsoft/security-devops-action@release/vNext
              id: msdo
              with: 
                config: '.gdn/e/credscan.gdnconfig'
        
            # Upload alerts to the Security tab
            - name: Upload alerts to Security tab
              uses: github/codeql-action/upload-sarif@v2
              with:
                category: 'Credscan'
                sarif_file: ${{ steps.msdo.outputs.sarifFile }}

            # Upload alerts file as a workflow artifact
            - name: Upload alerts file as a workflow artifact
              uses: actions/upload-artifact@v3
              with:  
                name: alerts
                path: ${{ steps.msdo.outputs.sarifFile }}